export { Home } from './Home'
export { Login } from './Login'
export { SignUp } from './SignUp'
export { Project } from './Project'
export { AddNew } from './AddNew'
export { Layout } from './Layout'
